### ISSUE TITLE
Left mouse

### ISSUE THREAD

**Issue by DarylRodrigo** [datamosh/ImpactJS-GUI#10]
Hey - this code over writes ig.input(ig.KEYS.MOUSE1, '') to mouse1 one by default, and theres no way you can undo that. Just for anybody wondering why left mouse isnt working, its because the state is 'mouse1' (would be awesome if this was in the readme, took me like 3 hours to realise)

**Comment by pdcprod** [comment]
Hi DarylRodrigo! that information is in the readme:
https://github.com/datamosh/ImpactJS-GUI#mouse-binds-important

Really really really sorry! :(
