### ISSUE TITLE
mouse binding

### ISSUE THREAD

**Issue by superprat** [datamosh/ImpactJS-GUI#4]
the plugin binds the mouse left click to 'mouse1'. You have to use the same binding everywhere else throughout the game. Perhaps it should mention that somewhere in the documentation?

Just saying, since I struggled with that for a while. Awesome plugin though, lifesaver..

**Comment by jspillers** [comment]
Yeah i just wasted 3 hours trying to figure out why my mouse binding wouldn't work... this is not really the plugins fault as you are just working with impacts lack of an event system, but it probably should be strongly stated in the readme.

**Comment by pdcprod** [comment]
Im sorry for causing you headache! :(
Added: https://github.com/datamosh/ImpactJS-GUI/blob/master/README.md#mouse-binds-important

**Comment by jspillers** [comment]
Thanks man... great plugin though seriously. Impact really surprised me with the lack of built in GUI (seems like a really critical thing to have). This code or something similar really needs to be part of the package.

**Comment by blakeage** [comment]
I propose the following addition to the plugin.  If this is added to the plugin, then if you have existing bindings in your app code for mouse1 (which I would think most people would), you can conditionally fire your app code only IF you're not clicking on a gui element:

In your update method, you could have this:

```
if( ig.input.pressed('mouse1') ) {
  if( !ig.gui.mouseIsOverElement() ) {
    // do whatever you want now that you know you're not clicking a button
    // ig.game.spawnEntity( EntityAcorn, ig.input.mouse.x, ig.input.mouse.y, { flip: false } );
  }
}
```

Plugin modification (additional method):

```
mouseIsOverElement: function() { // CUSTOM: Returns whether the current mouse position is over a gui element
      for (var i = 0; i < ig.gui.elements.length; i++) {
        var el = ig.gui.elements[ i ];

        if(ig.gui.cursor.pos.x >= el.pos.x && ig.gui.cursor.pos.x <= el.pos.x + el.size.x &&
          ig.gui.cursor.pos.y >= el.pos.y && ig.gui.cursor.pos.y <= el.pos.y + el.size.y && !el.disabled) {
          return true;
        }
      }
      return false;
    },
```
